= Project Context
<project-context>
== Purpose
<purpose>
The project aims to integrate Adversarial Autoencoders (AAE) with
machine learning methods to perform objective classification of
financial transactions. The goal represents a fraud detection system
that classifies transactions into three types: - Regular - Local Anomaly
\- Global Anomaly

The core approach involves training an AAE to generate latent vectors,
which are then used as features for supervised learning algorithms (SVM,
Random Forest, Naive Bayes) to improve classification performance
compared to using original features.

== Tech Stack
<tech-stack>
- #strong[Languages];: Python 3
- #strong[Deep Learning Framework];: PyTorch (`torch`, `torch.nn`)
- #strong[Machine Learning];: Scikit-learn (`sklearn`)
  - Classifiers: SVM, Random Forest, GaussianNB
  - Metrics: ROC, MAUC, Precision-Recall
  - Model Selection: StratifiedKFold
- #strong[Data Manipulation];: Pandas, NumPy
- #strong[Visualization];: Matplotlib, Seaborn

== Project Conventions
<project-conventions>
=== Code Style
<code-style>
- #strong[Naming];: Mixed use of `camelCase` (e.g., `latentVecDim`,
  `datasetFile`) and `snake_case` (e.g., `seed_value`, `clf_name`).
  Class names use `PascalCase`.
- #strong[Formatting];: 4-space indentation.
- #strong[Comments];: Generous use of comments to denote interions (e.g.,
  `importing pytorch libraries`, `specify first layer`).

=== Architecture Patterns
<architecture-patterns>
- #strong[Modular Components];: Network components are separated into
  individual files (e.g., `Encoder.py`, `Decoder.py`,
  `Discriminator.py`).
- #strong[Experiment Workflow];:
  + #strong[Train];: `validation_v0.py` trains the autoencoder.
  + #strong[Generate];: `generateDatasets.py` creates latent datasets in
    `latent_data_sets/`.
  + #strong[Experiment];: `MAUC_Exp.py` (latent features) and
    `MAUC_rawExp.py` (original features) run classification experiments.
  + #strong[Results];: Outputs are saved to `results/`.

=== Directory Structure
<directory-structure>
- `data/`: Input datasets.
- `latent_data_sets/`: Generated latent vector datasets.
- `models/`: Saved model artifacts.
- `results/`: Experiment outputs (plots, text files).
- `openspec/`: Project specifications and agent instructions.

=== Testing Strategy
<testing-strategy>
- #strong[Ad-hoc Testing];: Testing appears to be done via specific test
  scripts (e.g., `test_gaussianmixplot.py`, `testingBarPlot.py`) rather
  than a comprehensive unit test suite.
- #strong[Validation];: `validation_v0.py` serves as the primary
  validation script for the autoencoder training.

== Domain Context
<domain-context>
- #strong[Fraud Detection];: The domain focuses on identifying anomalies
  in financial data.
- #strong[MAUC];: Metric Area Under the Curve, a key performance metric
  used in this project.
- #strong[Latent Space];: The compressed representation of data
  generated by the autoencoder, critical for feature engineering in this
  pipeline.

== External Dependencies
<external-dependencies>
- #strong[PyTorch];: Core dependency for deep learning.
- #strong[Scikit-learn];: Essential for traditional ML classifiers and
  evaluation metrics.
